package router

import (
	"codebase/app/v1/deps"
	"github.com/labstack/echo/v4"

	"codebase/config"
	swaggerDoc "codebase/docs/swagger" // docs is generated by Swag CLI, you have to import it.
	swagger "github.com/swaggo/echo-swagger"
)

// Register godoc
// @title Majoo Auth Management API
// @version 1.0
// @description This is a Majoo Auth Management API Documentation.
// @termsOfService http://www.majoo.id/terms/
// @contact.name PT Majoo Teknologi Indonesia
// @contact.url https://www.majoo.id/
// @contact.message halo@majoo.id
// @securityDefinitions.bearer  BearerAuth
func Register(e *echo.Echo, deps deps.IDependency) {
	api := e.Group("/api")
	swaggerRouter(api)
}

func swaggerRouter(e *echo.Group) {
	swaggerDoc.SwaggerInfo.Host = config.GetConfig().BaseURL
	e.GET("/swagger/*", swagger.WrapHandler)
}
