// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	core "codebase/core"

	mock "github.com/stretchr/testify/mock"
)

// SubscriberUsecase is an autogenerated mock type for the SubscriberUsecase type
type SubscriberUsecase struct {
	mock.Mock
}

// ProcessMessage provides a mock function with given fields: ic, message
func (_m *SubscriberUsecase) ProcessMessage(ic *core.InternalContext, message interface{}) *core.CustomError {
	ret := _m.Called(ic, message)

	var r0 *core.CustomError
	if rf, ok := ret.Get(0).(func(*core.InternalContext, interface{}) *core.CustomError); ok {
		r0 = rf(ic, message)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.CustomError)
		}
	}

	return r0
}

// NewSubscriberUsecase creates a new instance of SubscriberUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubscriberUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *SubscriberUsecase {
	mock := &SubscriberUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
