// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	core "codebase/core"

	mock "github.com/stretchr/testify/mock"
)

// Pubsub is an autogenerated mock type for the Pubsub type
type Pubsub struct {
	mock.Mock
}

// Publish provides a mock function with given fields: ic, data
func (_m *Pubsub) Publish(ic *core.InternalContext, data []byte) *core.CustomError {
	ret := _m.Called(ic, data)

	var r0 *core.CustomError
	if rf, ok := ret.Get(0).(func(*core.InternalContext, []byte) *core.CustomError); ok {
		r0 = rf(ic, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.CustomError)
		}
	}

	return r0
}

// Subscribe provides a mock function with given fields: ic
func (_m *Pubsub) Subscribe(ic *core.InternalContext) *core.CustomError {
	ret := _m.Called(ic)

	var r0 *core.CustomError
	if rf, ok := ret.Get(0).(func(*core.InternalContext) *core.CustomError); ok {
		r0 = rf(ic)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.CustomError)
		}
	}

	return r0
}

// NewPubsub creates a new instance of Pubsub. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPubsub(t interface {
	mock.TestingT
	Cleanup(func())
}) *Pubsub {
	mock := &Pubsub{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
